### ISSUE TITLE
Multilingual jekyll example ?

### ISSUE THREAD

**Issue by vindarel** [smit1678/smit1678.github.com#2]
Hi Natan,

I just read your explanations on a multilingual Jekyll -so exactly what I was hoping for ! :)-, I looked for an example in your github and tweets… do you have an example somewhere ? What is the machinery that builds the website ?

Thanks a lot !

ps: you can also answer [a SO question](https://stackoverflow.com/questions/33451528/a-system-for-creating-multilingual-static-websites).

**Comment by smit1678** [comment]
hi @vindarel -- definitely have some examples. Check out Climatescope: https://github.com/climatescope/climatescope-2014. It uses a [translation file](https://github.com/climatescope/climatescope-2014/blob/master/_data/i18n_strings.yml) to manage most of the UI elements and then english and spanish pages are organized with `_en` or `_es`. 

You could also look at https://github.com/tristen/multilingual, but this is based on previous versions of Jekyll. Jekyll's new [collections](http://jekyllrb.com/docs/collections/) feature changes the way it can be done.

**Comment by vindarel** [comment]
Thank you very much.

On my side I found [statirator](https://github.com/MeirKriheli/statirator), which can be seen as "frozen-django".
